name: "🐛 Bug Report for Terra (including AnVIL/BioData Catalyst)"
description: Create a new ticket for a bug encountered using Terra.
title: "🐛 [BUG] - <title>"
labels: [
  "bug", "terra"
]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: My question isn't about setting up a Terra account or billing -- please see [Terra Support](https://support.terra.bio/) for that instead!
          required: true
        - label: I understand this issue form is PUBLIC and anything I write here, as well as any replies I make via GitHub.com or my GitHub-enabled email, will be PUBLIC.
          required: true
        - label: I affirm that nothing included in attached logs or reproducible steps contains PHI or other confidential data.
          required: true

  - type: textarea
    id: version
    attributes:
      label: "What version of TB-D are you running?"
      description: When TB-D is selected in Terra, you will see the text "Version" next to a drop-down selector. Please enter the version you had selected when the issue occurred.
      placeholder: Place version information here...
    validations:
      required: true
 
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true

  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description:  If possible to do so while EXCLUDING ANY AND ALL CONFIDENTIAL INFORMATION, please copy and paste any relevant log output.
      render: bash
    validations:
      required: false

